const $=s=>document.querySelector(s); const app=$('#app');
const defaults={machine:'9250',crop:'Canola',customer:'',hc:true,mode:'Performance',thresh:'Medium',freq:'Medium',symptoms:[],sample:{},tailings:'',conditions:{},setup:{},ranges:{},sens:{},pan:{},history:[]};
let S=JSON.parse(localStorage.getItem('co_state')||'null')||structuredClone(defaults); let page='home';
const save=()=>{localStorage.setItem('co_state',JSON.stringify(S));status()}; const val=(o,k)=>o[k]??''; const num=x=>x===''?null:Number(x);
function status(){ $('#status').textContent=`${S.machine||'No machine'} • ${S.crop||'No crop'} • Harvest Command ${S.hc?'ON':'OFF'}${S.hc?' • '+S.mode:''}` }
const machines=['8230','8240','8250','9230','9240','9250','AF9','AF10','AF11']; const crops=['Canola','Wheat','Barley','Oats','Peas','Lentils','Flax','Soybeans','Corn','Other'];
const symptoms=['Unthreshed grain / heads / pods','Rotor loss / free grain in straw','Sieve loss / free grain in chaff','Cracked / broken grain','Dirty sample / MOG','Stalks / straw in grain tank','High tailings','Grain blowing out','Poor capacity','Plugging / overloading','Uneven / hill loss','Harvest Command hunting'];
function field(label,key,obj=S.setup,type='number'){return `<label>${label}</label><input type='${type}' data-bind='${key}' value='${val(obj,key)}'>`}
function select(label,key,arr,obj=S){return `<label>${label}</label><select data-bind='${key}'>${arr.map(x=>`<option ${obj[key]===x?'selected':''}>${x}</option>`).join('')}</select>`}
function card(t,b){return `<section class='card'><h2>${t}</h2>${b}</section>`}
function home(){app.innerHTML=`<h1>Combine Optimizer</h1>${card('Field Setup',`${select('Combine','machine',machines)}${select('Crop','crop',crops)}${field('Customer / Farm','customer',S,'text')}<label>Harvest Command</label><div class='choice'><button data-hc='1' class='${S.hc?'on':''}'>ON</button><button data-hc='0' class='${!S.hc?'on':''}'>OFF</button></div>`)}${card('Start Here',`<button class='btn' data-go='current'>CURRENT MACHINE SETUP</button><button class='btn' data-go='hc'>HARVEST COMMAND</button><button class='btn' data-go='diagnose'>DIAGNOSE A PROBLEM</button><button class='btn secondary' data-go='guide'>SETTINGS GUIDE</button><button class='btn secondary' data-go='sensors'>SENSORS / LEARN</button><button class='btn secondary' data-go='simulator'>X-RAY SIMULATOR</button><button class='btn light' data-go='check'>START-OF-DAY CHECK</button>`)}<div class='note'><b>Field rule:</b> Verify the actual loss first. Attached grain points to threshing; loose grain with straw points to separation; loose grain with chaff points to cleaning. Change one area at a time.</div>`}
function current(){app.innerHTML=`<h1>Current Machine Setup</h1>${card('Machine Settings',`<div class='grid'>${field('Rotor Speed (RPM)','rotor')}${field('Concave Clearance','concave')}${field('Fan Speed (RPM)','fan')}${field('Pre-Sieve','presieve')}${field('Upper Sieve','upper')}${field('Lower Sieve','lower')}${field('Cage Vanes','vanes')}${field('Ground Speed','speed')}${field('Engine Load (%)','load')}${field('Moisture (%)','moisture')}${field('Throughput / Yield','throughput')}</div><button class='btn' data-go='hc'>NEXT: HARVEST COMMAND</button>`)}${card('Machine Configuration',`${field('Concave / grate configuration','concaveType',S.setup,'text')}${field('Rasp / separator configuration','rasp',S.setup,'text')}${field('Header type / width','header',S.setup,'text')}${field('Residue setup','residue',S.setup,'text')}`)}`}
function hc(){const r=['rotor','fan','presieve','upper','lower','vanes'];app.innerHTML=`<h1>Harvest Command</h1><div class='tabs'><button class='on'>OVERVIEW</button><button data-scroll='ranges'>RANGES</button><button data-scroll='sens'>SENSITIVITIES</button><button data-scroll='advanced'>ADVANCED</button><button data-go='sensors'>SENSORS</button></div>${card('Overview',`${select('Operating Mode','mode',['Performance','Grain Quality','Max Throughput','Fixed Throughput'])}${select('Threshing Condition','thresh',['Easy','Medium','Hard'])}${select('Adjustment Frequency','freq',['Low','Medium','High'])}<div class='info'><b>Mode guide:</b> Performance = general balance. Grain Quality = protect sample/damage. Max Throughput = acres/hour priority. Fixed Throughput = steadier crop flow.</div>`)}<section id='ranges'>${card('Allowed Ranges',r.map(k=>`<h3>${k.toUpperCase()}</h3><div class='grid3'>${field('MIN',k+'Min',S.ranges)}${field('CURRENT',k+'Cur',S.ranges)}${field('MAX',k+'Max',S.ranges)}</div>`).join(''))}</section><section id='sens'>${card('Sensitivities',`${field('Rotor Loss','rotorLoss',S.sens)}${field('Sieve Loss','sieveLoss',S.sens)}${field('Grain Quality','quality',S.sens)}${field('MOG','mog',S.sens)}<p class='muted'>Enter the values shown on your monitor. The app does not assume a universal sensitivity scale.</p>`)}</section><section id='advanced'>${card('Advanced / Headland',`${field('Maximum Rotor Speed','maxRotor',S.setup)}${field('Sieve Load Configuration','sieveLoad',S.setup,'text')}${field('Headland Fan Offset','headFan',S.setup)}${field('Headland Upper Sieve Offset','headUpper',S.setup)}${field('Headland Lower Sieve Offset','headLower',S.setup)}${field('Headland Pre-Sieve Offset','headPre',S.setup)}`)}</section>`}
function diagnose(){app.innerHTML=`<h1>Diagnose Problem</h1>${card('What is wrong?',`<p>Select everything you are seeing.</p><div class='choice'>${symptoms.map(x=>`<button data-sym='${x}' class='${S.symptoms.includes(x)?'on':''}'>${x}</button>`).join('')}</div>`)}${card('Crop Conditions',`${select('Straw / crop condition','straw',['Normal','Dry / brittle','Tough / green','Very heavy'],S.conditions)}${select('Crop position','position',['Standing','Lodged / uneven'],S.conditions)}${select('Time / condition change','time',['Stable','Morning / damp','Afternoon / dry','Evening / toughening'],S.conditions)}`)}${card('Grain Tank Sample',`${select('Cracked grain','cracked',['None','Low','Medium','High'],S.sample)}${select('MOG / chaff','mog',['None','Low','Medium','High'],S.sample)}${select('Unthreshed material','unthreshed',['None','Low','Medium','High'],S.sample)}${select('Stems / stalks','stems',['None','Low','Medium','High'],S.sample)}${select('Overall sample','overall',['Clean','Acceptable','Poor'],S.sample)}`)}${card('Tailings',`${select('What is mostly in the tailings?','tailings',['','Mostly clean grain','Unthreshed grain / heads','Mostly chaff / MOG','Damaged grain','Sudden spike / unknown'],S)}<button class='btn' data-go='pans'>NEXT: VERIFY WITH DROP PANS</button><button class='btn secondary' data-go='recommend'>SKIP TO RECOMMENDATIONS</button>`)}`}
const cropDensityLbBu={
  'Canola':50,'Wheat':60,'Barley':48,'Oats':34,'Peas':60,'Lentils':60,'Flax':56,'Soybeans':60,'Corn':56
};
function lossCalc(){
  const p=S.pan||{};
  const density=Number(p.density), cut=Number(p.cutWidth), discharge=Number(p.dischargeWidth);
  const area=Number(p.catchArea), grams=Number(p.lossWeight), yieldBu=Number(p.yield);
  if(!(density>0&&cut>0&&discharge>0&&area>0&&grams>=0)) return null;
  const gramsPerFt2=grams/area;
  const lbPerAcreInDischarge=gramsPerFt2*43560/453.59237;
  const lbPerAcreField=lbPerAcreInDischarge*(discharge/cut);
  const buAc=lbPerAcreField/density;
  const pct=yieldBu>0?(buAc/yieldBu)*100:null;
  return {gramsPerFt2,lbPerAcreField,buAc,pct};
}
function setCropDensityDefault(){
  if(!S.pan)S.pan={};
  if((S.pan.density==null||S.pan.density==='')&&cropDensityLbBu[S.crop]) S.pan.density=cropDensityLbBu[S.crop];
}
function pans(){
  setCropDensityDefault();
  const L=lossCalc();
  const result=L
    ? `<div class='lossResult'><div><span>COMBINE LOSS</span><strong>${L.buAc.toFixed(2)} bu/ac</strong></div><div><span>LOSS OF YIELD</span><strong>${L.pct==null?'—':L.pct.toFixed(2)+'%'}</strong></div><div><span>LOSS WEIGHT / FIELD AREA</span><strong>${L.lbPerAcreField.toFixed(1)} lb/ac</strong></div></div>`
    : `<div class='info'><b>Enter Density, Cut Width, Discharge Width, Catch Area and Loss Weight to calculate combine loss.</b></div>`;
  app.innerHTML=`<h1>Drop Pans</h1>
  ${card('Combine Loss Results',`
    <div class='grid'>
      <div><label>Crop</label><input value='${S.crop}' disabled></div>
      ${field('Density (lb/bu)','density',S.pan)}
      ${field('Yield (bu/ac)','yield',S.pan)}
      ${field('Cut Width (ft)','cutWidth',S.pan)}
      ${field('Discharge Width (ft)','dischargeWidth',S.pan)}
      ${field('Ground Speed (mph)','groundSpeed',S.pan)}
      ${field('Catch Area (ft²)','catchArea',S.pan)}
      ${field('Loss Weight (grams)','lossWeight',S.pan)}
    </div>
    <p class='muted'>Density is the bushel weight used for this loss calculation. A crop default is filled in when available, but you can change it to the value you want to use.</p>
    ${result}
    <div class='formulaBox'><b>How it is calculated</b><br>Loss weight is converted from grams over the catch area to lb/ac, corrected for discharge width versus cut width, then divided by density (lb/bu). Yield is used to calculate percent loss. Ground speed is saved with the test for field context.</div>
  `)}
  ${card('Physical Loss Classification',`
    ${select('Pre-harvest loss','pre',['Not checked','Low / acceptable','High'],S.pan)}
    ${select('Header loss','headerLoss',['Not checked','Low / acceptable','High'],S.pan)}
    ${select('Rotor / separation loss','rotorLoss',['Not checked','Low / acceptable','High'],S.pan)}
    ${select('Cleaning / sieve loss','sieveLoss',['Not checked','Low / acceptable','High'],S.pan)}
    ${select('Main physical loss location','main',['Not sure','Header','Rotor / separation','Cleaning system','No significant physical loss'],S.pan)}
    <label>Notes</label><textarea data-bind='notes'>${val(S.pan,'notes')}</textarea>
    <button class='btn' data-go='recommend'>BUILD FINAL RECOMMENDATIONS</button>
  `)}`;
}
function recs(){let R=buildRecommendations();app.innerHTML=`<h1>Final Recommendations</h1>${card('Diagnosis',`<b>Primary suspect:</b> ${R.area}<br><b>Confidence:</b> ${R.conf}<p>${R.why}</p>`)}${R.items.map((x,i)=>`<div class='card rank ${i===1?'two':i===2?'three':''}'><h2>${i+1} — ${i===0?'CHANGE FIRST':i===1?'IF NEEDED':'NEXT'}</h2><b>${x.title}</b><p>${x.text}</p>${x.hc?`<div class='info'><b>Harvest Command:</b> ${x.hc}</div>`:''}</div>`).join('')}${card("DON'T CHANGE YET",R.dont)}${card('RETEST',`Let crop flow stabilize, physically recheck loss and sample, then record the result.<div class='choice'><button data-result='BETTER'>BETTER</button><button data-result='SAME'>SAME</button><button data-result='WORSE'>WORSE</button></div><button class='btn good' data-save-setup='1'>SAVE SUCCESSFUL SETUP</button>`)}`}
function buildRecommendations(){let s=S.symptoms,p=S.pan;let area='Needs physical verification',conf='LOW',why='The app needs a symptom or physical loss result before making a strong call.',items=[];const has=t=>s.some(x=>x.includes(t));
if(p.main==='Rotor / separation'||has('Rotor loss')){area='Rotor / separation';conf=p.main==='Rotor / separation'?'HIGH':'MEDIUM';why='Free threshed grain traveling with straw points to separation loss.';items=[{title:'Verify separation area / concave-grate condition',text:'Check that the crop has enough open separation area and that concaves/grates are not plugged, damaged or poorly matched.'},{title:'Test rotor speed one direction at a time',text:'Test slower first and physically recheck. If it does not improve, return to baseline and test faster. Keep the direction that reduces physical loss.',hc:'Make sure the rotor range is not pinned against the direction the physical test needs.'},{title:'Add separation time / reduce crop load',text:'Use cage-vane retention where applicable. If loss rises with crop load, reduce feedrate/ground speed.'}];}
else if(p.main==='Cleaning system'||has('Sieve loss')||has('Grain blowing')){area='Cleaning system';conf=p.main==='Cleaning system'?'HIGH':'MEDIUM';why='Loose grain associated with chaff points to the cleaning shoe. First distinguish overload from blow-out.';if(has('Grain blowing'))items=[{title:'Reduce fan if physical evidence confirms blow-out',text:'Excess air can carry light grain out with chaff. Make a small change and recheck.'},{title:'Verify sieve openings',text:'Do not chase fan alone. Confirm the cleaning area is not unnecessarily restricted.'},{title:'Recheck at a stable crop load',text:'If loss remains, inspect cleaning-system condition, sensor agreement and calibration.'}];else items=[{title:'Reduce crop load / add cleaning passage',text:'If loss improves when you slow down, the shoe is likely capacity-limited. Open the restrictive sieve enough to pass grain.'},{title:'Balance upper and lower sieves',text:'Upper too closed can create restriction and loss. Lower too closed can reject clean grain into tailings.'},{title:'Optimize fan after overload is addressed',text:'Use fan to stratify and clean, but verify you are not blowing grain out.',hc:'Increase Sieve Loss priority only after physical loss confirms the cleaning system is the problem.'}];}
else if(has('Unthreshed')||S.sample.unthreshed==='High'){area='Threshing';conf='MEDIUM';why='Grain still attached to heads or pods is a threshing problem, not a cleaning problem.';items=[{title:'Increase effective threshing',text:'Increase rotor RPM from the current baseline and recheck the sample.'},{title:'Tighten concave if needed',text:'Reduce concave clearance carefully if more threshing action is required.',hc:'Concave clearance is an operator setting; Harvest Command cannot correct it automatically.'},{title:'Reduce feedrate / inspect hardware',text:'If the first two changes do not solve it, reduce crop load and inspect concaves, rasp bars and configuration.'}];}
else if(has('Cracked')||S.sample.cracked==='High'){area='Over-threshing / rethreshing';conf='MEDIUM';why='Cracked grain usually calls for less threshing aggression and less unnecessary recirculation.';items=[{title:'Reduce rotor speed',text:'Back rotor RPM down from the current baseline and inspect grain quality.'},{title:'Widen concave clearance',text:'If damage remains, open the concave to reduce aggression.'},{title:'Check tailings / rethreshing',text:'High recirculation can create damage even when the first pass is acceptable.',hc:'Increase Grain Quality priority if protecting kernels matters more than maximum throughput.'}];}
else if(has('Dirty')||S.sample.mog==='High'){area='Cleaning / upstream MOG';conf='MEDIUM';why='First identify whether the material is light chaff or heavy/unthreshed material.';items=[{title:'If light chaff: increase fan carefully',text:'More air may improve separation of light MOG. Verify physical loss so grain is not blown out.'},{title:'Tighten upper sieve slightly if needed',text:'Do this after fan and upstream causes are checked.'},{title:'If straw/pods are heavy: fix upstream cause',text:'Reduce over-processing or correct threshing instead of hiding it with cleaning settings.',hc:'MOG sensitivity can favor a cleaner sample, but it should not hide an upstream threshing problem.'}];}
else if(has('High tailings')||S.tailings){area='Tailings / upstream cause';conf=S.tailings?'MEDIUM':'LOW';why='Tailings are most useful when you identify what they contain.';if(S.tailings==='Mostly clean grain')items=[{title:'Open the restrictive sieve',text:'Clean grain in returns points to cleaning restriction.'},{title:'Balance fan and shoe load',text:'Keep enough air for stratification without excessive blow-out.'},{title:'Reduce load if required',text:'If tailings rise with throughput, the shoe may be capacity-limited.'}];else if(S.tailings==='Unthreshed grain / heads')items=[{title:'Fix threshing first',text:'Increase effective threshing with rotor/concave before touching cleaning settings.'},{title:'Reduce feedrate if overloaded',text:'Give the threshing system time to do its job.'},{title:'Inspect threshing hardware',text:'Check concaves, rasp bars and crop configuration if the problem persists.'}];}
if(!items.length)items=[{title:'Physically classify the loss',text:'Check pre-harvest, header, tank sample, tailings and residue. Decide whether grain is attached, loose with straw, or loose with chaff.'},{title:'Check for a pinned Harvest Command setting',text:'Watch which setting repeatedly reaches its minimum or maximum.'},{title:'Inspect before chasing numbers',text:'If physical evidence and monitor readings disagree, verify sensors, actuators, calibration, plugging and wear.'}];
let dont=area.includes('Threshing')?'Do not use fan or sieve settings to hide an upstream threshing problem.':area.includes('Cleaning')?'Do not make rotor changes unless the residue/sample also shows a threshing or separation problem.':'Do not change several settings at once. Make one controlled change and recheck.';return{area,conf,why,items,dont}}
function setups(){let saved=JSON.parse(localStorage.getItem('co_setups')||'[]');app.innerHTML=`<h1>Saved Setups</h1>${saved.length?saved.map((x,i)=>card(`${x.machine} • ${x.crop}`,`<b>${x.customer||'No customer'}</b><p>${new Date(x.saved).toLocaleString()}</p><button class='btn light' data-load='${i}'>LOAD SETUP</button>`)).join(''):'<div class="card">No saved setups yet.</div>'}${card('Backup / Restore',`<button class='btn secondary' id='export'>EXPORT BACKUP</button><label>Import backup JSON</label><input id='import' type='file' accept='.json'>`)}`}
const sensors250=['Flow / yield sensor','Rotor speed sensors','Rotor loss sensors','Cage-vane position sensor','Engine load sensor','Inclination sensor','Grain camera','Pre-sieve position sensor','Upper sieve position sensor','Sieve loss sensor','Sieve pressure sensors','Lower sieve position sensor','Tailings volume sensor','Fan speed sensor','Ground speed sensor','Ground-drive pressure sensor'];
function sensors(){app.innerHTML=`<h1>Sensors / Learn</h1>${card('250 Series Harvest Command',`<p>Earlier Harvest Command architecture uses sensor inputs to judge crop load, loss, quality and machine position. Verify physical loss when a sensor indication does not make sense.</p>${sensors250.map(x=>`<div class='sensor'><b>${x}</b></div>`).join('')}`)}${card('AF Series Difference',`Current AF Harvest Command architecture adds independent front/rear cleaning control and Cross-Flow Plus side-shake authority. Diagnose AF cleaning behavior by section instead of treating the shoe as one single adjustment.`)}`}
function simulator(){
 const n=v=>Number(v)||0,st=S.setup||{},r=S.ranges||{},rotor=n(st.rotor)||n(r.rotorCur),fan=n(st.fan)||n(r.fanCur),speed=n(st.speed),load=n(st.load),conc=n(st.concave),pre=n(st.presieve)||n(r.presieveCur),upper=n(st.upper)||n(r.upperCur),lower=n(st.lower)||n(r.lowerCur),issue=S.pan?.main||'';
 app.innerHTML=`<h1>X-Ray Simulator</h1><div class='note'><b>Teaching simulator:</b> This is a diagnostic visualization, not a physics model. It shows general material flow and uses your entered settings and physical diagnosis to highlight areas to inspect.</div>
 ${card(`${S.machine||'Combine'} • ${S.crop||'Crop'}`,`<div class='simLegend'><span class='grainC'>● Grain</span><span class='strawC'>● Straw</span><span class='chaffC'>● Chaff / MOG</span></div><div class='xray'>
 <div class='flow'><b>1 — HEADER + FEEDER</b><small>Crop is cut, gathered and delivered into the machine.</small><div class='stream'><i class='grainC'>•••</i><i class='strawC'>━━━━</i></div></div><div class='down'>↓</div>
 <button class='flow ${load>=90?'hot':''}' data-sim='rotor'><b>2 — ROTOR + CONCAVES</b><small>Thresh grain from heads / pods.</small><div class='stream'><i class='grainC'>•••• ↓</i><i class='strawC'>━━━━ →</i></div></button><div class='down'>↓</div>
 <button class='flow ${issue==='Rotor / separation'?'hot':''}' data-sim='separation'><b>3 — SEPARATION</b><small>Released grain separates from straw before residue exits.</small><div class='stream'><i class='grainC'>••• ↓</i><i class='strawC'>━━━━ → RESIDUE</i></div></button><div class='down'>↓</div>
 <button class='flow ${issue==='Cleaning system'?'hot':''}' data-sim='shoe'><b>4 — PRE-SIEVE + CLEANING SHOE</b><small>Air and sieves separate grain from chaff / MOG.</small><div class='stream'><i class='chaffC'>≈≈≈ ↑ RESIDUE</i><i class='grainC'>•••• ↓</i></div></button><div class='down'>↓</div>
 <button class='flow' data-sim='tank'><b>5 — CLEAN GRAIN + TAILINGS</b><small>Clean grain goes to the tank. Returns recirculate material needing another pass.</small></button></div><div id='simExplain' class='info'><b>Tap a section of the X-ray</b> to learn what happens there and which settings affect it.</div>`)}
 ${card('Your Current Settings',`<div class='simStats'><div><b>${rotor||'—'}</b><small>Rotor RPM</small></div><div><b>${conc||'—'}</b><small>Concave</small></div><div><b>${fan||'—'}</b><small>Fan RPM</small></div><div><b>${pre||'—'}</b><small>Pre-Sieve</small></div><div><b>${upper||'—'}</b><small>Upper Sieve</small></div><div><b>${lower||'—'}</b><small>Lower Sieve</small></div><div><b>${speed||'—'}</b><small>Ground Speed</small></div><div><b>${load?load+'%':'—'}</b><small>Engine Load</small></div></div><button class='btn' data-go='current'>CHANGE CURRENT SETTINGS</button><button class='btn secondary' data-go='recommend'>VIEW RECOMMENDATIONS</button>`)}
 ${card('Fast Diagnosis',`<p><b>Grain still attached:</b> THRESHING.</p><p><b>Loose grain + straw:</b> SEPARATION.</p><p><b>Loose grain + chaff:</b> CLEANING.</p><p>A red section means your entered information says that area deserves attention. Verify actual loss before changing settings.</p>`)}`;
 document.querySelectorAll('[data-sim]').forEach(b=>b.onclick=()=>{const t={rotor:`<b>Rotor + Concaves</b><br>Rotor speed and concave clearance affect threshing intensity. Too little effective threshing can leave grain attached. Too much aggression can damage grain and create extra MOG.`,separation:`<b>Separation</b><br>Already-threshed grain still mixed with straw needs time and open separation area to fall out. Crop load, rotor behavior, cage-vane retention and separation hardware/configuration can affect this area.`,shoe:`<b>Pre-Sieve + Cleaning Shoe</b><br>The pre-sieve, upper/lower sieves and cleaning fan work together to separate grain from chaff. If grain is leaving with chaff, determine whether the shoe is overloaded or grain is being blown out.`,tank:`<b>Grain Tank + Tailings</b><br>The tank sample shows the final result. Tailings help diagnose the cause: clean grain can indicate restriction, while unthreshed material points upstream toward threshing.`};$('#simExplain').innerHTML=t[b.dataset.sim]||'';});
}
function guide(){app.innerHTML=`<h1>Settings Guide</h1>${[['Rotor RPM','Higher can add threshing/agitation; lower can reduce damage. For rotor loss, test both directions from baseline and verify physically.'],['Concave clearance','Tighter adds threshing intensity; wider reduces aggression. Operator controlled.'],['Cage vanes','More retention gives crop more separation opportunity; faster crop travel favors capacity.'],['Pre-sieve','Too closed can restrict early passage; too open can pass too much material.'],['Upper sieve','More open adds passage/capacity; more closed can clean the sample but may restrict the shoe.'],['Lower sieve','More open lets clean grain pass and can reduce clean grain in tailings; too open can reduce final cleaning.'],['Cleaning fan','Higher can remove light MOG; too high can blow light grain out.'],['Ground speed / feedrate','If loss rises with crop load and improves when slowing, capacity is limiting.']].map(x=>card(x[0],x[1])).join('')}`}
function check(){app.innerHTML=`<h1>Start-of-Day Check</h1>${card('Before Harvesting',`<p>☐ Correct crop and Harvest Command mode</p><p>☐ Max ground speed / engine limits appropriate</p><p>☐ Rotor, fan, sieve and vane ranges not accidentally restricted</p><p>☐ Required calibrations complete</p><p>☐ Rotor rasp bars and concaves inspected</p><p>☐ Cleaning system free of plugging/damage</p><p>☐ Loss sensor areas / wiring inspected</p><p>☐ Grain camera area checked</p><p>☐ Leveling / Cross-Flow functions checked where equipped</p><p>☐ Header and feeder delivering crop smoothly</p><p>☐ Physical baseline loss established</p>`)}`}
function render(){document.querySelectorAll('#nav button').forEach(b=>b.classList.toggle('active',b.dataset.page===page));({home,diagnose,pans,recommend:recs,setups,current,hc,sensors,guide,check,simulator}[page]||home)();bind();status()}
function bind(){document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>{page=b.dataset.go;render()});document.querySelectorAll('[data-bind]').forEach(el=>el.onchange=()=>{let key=el.dataset.bind;let target=S;if(page==='current')target=S.setup;else if(page==='pans')target=S.pan;else if(page==='diagnose'){if(['straw','position','time'].includes(key))target=S.conditions;else if(['cracked','mog','unthreshed','stems','overall'].includes(key))target=S.sample;}else if(page==='hc'){if(key.endsWith('Min')||key.endsWith('Cur')||key.endsWith('Max'))target=S.ranges;else if(['rotorLoss','sieveLoss','quality','mog'].includes(key))target=S.sens;else if(!['mode','thresh','freq'].includes(key))target=S.setup;}target[key]=el.type==='number'?num(el.value):el.value;save();if(page==='pans'&&['density','yield','cutWidth','dischargeWidth','groundSpeed','catchArea','lossWeight'].includes(key))render()});document.querySelectorAll('[data-hc]').forEach(b=>b.onclick=()=>{S.hc=b.dataset.hc==='1';save();render()});document.querySelectorAll('[data-sym]').forEach(b=>b.onclick=()=>{let x=b.dataset.sym;S.symptoms=S.symptoms.includes(x)?S.symptoms.filter(y=>y!==x):[...S.symptoms,x];save();render()});document.querySelectorAll('[data-scroll]').forEach(b=>b.onclick=()=>document.getElementById(b.dataset.scroll)?.scrollIntoView({behavior:'smooth'}));document.querySelectorAll('[data-result]').forEach(b=>b.onclick=()=>{S.history.push({at:new Date().toISOString(),result:b.dataset.result,symptoms:[...S.symptoms],setup:{...S.setup}});save();alert('Result saved: '+b.dataset.result)});document.querySelectorAll('[data-save-setup]').forEach(b=>b.onclick=saveSetup);document.querySelectorAll('[data-load]').forEach(b=>b.onclick=()=>{let a=JSON.parse(localStorage.getItem('co_setups')||'[]');S=structuredClone(a[Number(b.dataset.load)]);delete S.saved;save();page='home';render()});let ex=$('#export');if(ex)ex.onclick=exportBackup;let im=$('#import');if(im)im.onchange=importBackup}
function saveSetup(){let a=JSON.parse(localStorage.getItem('co_setups')||'[]');a.unshift({...structuredClone(S),saved:new Date().toISOString()});localStorage.setItem('co_setups',JSON.stringify(a));alert('Setup saved on this device.')}
function exportBackup(){let blob=new Blob([JSON.stringify({state:S,setups:JSON.parse(localStorage.getItem('co_setups')||'[]')},null,2)],{type:'application/json'}),u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download='combine-optimizer-backup.json';a.click();URL.revokeObjectURL(u)}
function importBackup(e){let f=e.target.files[0];if(!f)return;let r=new FileReader();r.onload=()=>{try{let d=JSON.parse(r.result);S=d.state||structuredClone(defaults);localStorage.setItem('co_setups',JSON.stringify(d.setups||[]));save();render();alert('Backup restored.')}catch{alert('That backup file could not be read.')}};r.readAsText(f)}
const nav=document.querySelector('#nav');
if(nav && !nav.querySelector("[data-page='simulator']")){
  const sim=document.createElement('button');
  sim.dataset.page='simulator';
  sim.textContent='SIMULATOR';
  nav.appendChild(sim);
}
document.querySelectorAll('#nav button').forEach(b=>b.onclick=()=>{page=b.dataset.page;render()});
let deferred;
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferred=e;$('#installBtn').hidden=false});
$('#installBtn').onclick=async()=>{if(deferred){deferred.prompt();deferred=null;$('#installBtn').hidden=true}};
function setOfflineStatus(text,ready=false){const el=$('#offlineStatus');if(!el)return;el.textContent=text;el.style.background=ready?'#176b35':'#7a1d1d';}
async function verifyOfflineCache(){
  if(!('serviceWorker' in navigator)){setOfflineStatus('OFFLINE CACHE: NOT SUPPORTED');return;}
  try{
    await navigator.serviceWorker.register('./service-worker.js',{scope:'./'});
    await navigator.serviceWorker.ready;
    const names=await caches.keys();
    const name=names.find(n=>n==='combine-optimizer-github-pages-v5');
    if(!name){setOfflineStatus('OFFLINE CACHE: NOT READY — STAY ONLINE AND REFRESH');return;}
    const cache=await caches.open(name);
    const required=['./index.html','./style.css','./app.js','./manifest.json'];
    const checks=await Promise.all(required.map(x=>cache.match(x)));
    if(checks.every(Boolean)) setOfflineStatus(navigator.onLine?'OFFLINE READY ✓':'OFFLINE MODE ✓',true);
    else setOfflineStatus('OFFLINE CACHE: INCOMPLETE — REFRESH WHILE ONLINE');
  }catch(err){setOfflineStatus('OFFLINE CACHE ERROR — REFRESH WHILE ONLINE');}
}
window.addEventListener('online',()=>verifyOfflineCache());
window.addEventListener('offline',()=>setOfflineStatus('OFFLINE MODE ✓',true));
window.addEventListener('load',verifyOfflineCache);
render();
